/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Lance Salera
 */
public class Subscribe extends javax.swing.JFrame {

    /**
     * Creates new form Subscribe
     */
    String user;
    Connect conn;
    public Subscribe(String username) {
        initComponents();
        conn = new Connect();
        user = username;
    }

    public Subscribe() {
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSubscriptionType = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubscriptionType = new javax.swing.JLabel();
        rbBasic = new javax.swing.JRadioButton();
        rbCorporate = new javax.swing.JRadioButton();
        lblPeriod = new javax.swing.JLabel();
        tfPeriod = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        lblAmountPayable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAmountPayable = new javax.swing.JTextArea();
        lblPayment = new javax.swing.JLabel();
        tfPayment = new javax.swing.JTextField();
        btnMakePayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Subscribe");

        lblSubscriptionType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubscriptionType.setText("Subscription Type:");

        bgSubscriptionType.add(rbBasic);
        rbBasic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbBasic.setText("Basic");
        rbBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBasicActionPerformed(evt);
            }
        });

        bgSubscriptionType.add(rbCorporate);
        rbCorporate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbCorporate.setText("Corporate");
        rbCorporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCorporateActionPerformed(evt);
            }
        });

        lblPeriod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPeriod.setText("Subscription Period (Months):");

        tfPeriod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfPeriod.setText("0");
        tfPeriod.setEnabled(false);
        tfPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPeriodActionPerformed(evt);
            }
        });

        btnCalc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalc.setText("Calculate");
        btnCalc.setEnabled(false);
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        lblAmountPayable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAmountPayable.setText("Amount Payable:");

        taAmountPayable.setColumns(20);
        taAmountPayable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taAmountPayable.setLineWrap(true);
        taAmountPayable.setRows(5);
        taAmountPayable.setText("0");
        taAmountPayable.setWrapStyleWord(true);
        taAmountPayable.setEnabled(false);
        jScrollPane1.setViewportView(taAmountPayable);

        lblPayment.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPayment.setText("Enter Payment:");

        tfPayment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPayment.setText("0");
        tfPayment.setEnabled(false);
        tfPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPaymentActionPerformed(evt);
            }
        });

        btnMakePayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMakePayment.setText("Make Payment");
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblTitle))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMakePayment)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblPeriod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblSubscriptionType)
                                .addGap(18, 18, 18)
                                .addComponent(rbBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCorporate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblAmountPayable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPayment)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubscriptionType)
                    .addComponent(rbBasic)
                    .addComponent(rbCorporate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPeriod)
                        .addComponent(tfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmountPayable)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment)
                    .addComponent(tfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMakePayment)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBasicActionPerformed
        // TODO add your handling code here:
        tfPeriod.setEnabled(false);
        btnCalc.setEnabled(false);
        tfPayment.setEnabled(false);
    }//GEN-LAST:event_rbBasicActionPerformed

    private void rbCorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCorporateActionPerformed
        // TODO add your handling code here:
        tfPeriod.setEnabled(true);
        btnCalc.setEnabled(true);
        tfPayment.setEnabled(true);
    }//GEN-LAST:event_rbCorporateActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int speriod = Integer.parseInt(tfPeriod.getText());
        double result = (double) 1299.0 * speriod;
        taAmountPayable.setText(Double.toString(result));
    }//GEN-LAST:event_btnCalcActionPerformed

    private void tfPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPaymentActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here:
        try {
            String stype;
            if(rbBasic.isSelected()) {
                stype = rbBasic.getText();
            } else if(rbCorporate.isSelected()) {
                stype = rbCorporate.getText();
            } else {
                stype = "";
            }
            int speriod = Integer.parseInt(tfPeriod.getText());
            double amountPayable;
            if(stype.equals("Basic")) {
                amountPayable = 0;
                tfPayment.setText("0");
            } else {
                amountPayable = Double.parseDouble(taAmountPayable.getText());
            }
            double payment = Double.parseDouble(tfPayment.getText());
            if(stype.equals("")) {
                throw new IllegalArgumentException("Input required!");
            }
            if(payment >= amountPayable) {
                Subscriber s = new Subscriber(stype, speriod, user);
                conn.subscribe(s);
                JOptionPane.showMessageDialog(pnlMain, "Subscribed!");
            } else {
                throw new IllegalArgumentException("Insufficient payment");
            }
        } catch(IllegalArgumentException i) {
            JOptionPane.showMessageDialog(pnlMain, i.getMessage());
        }
        
    }//GEN-LAST:event_btnMakePaymentActionPerformed

    private void tfPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPeriodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subscribe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subscribe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subscribe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subscribe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subscribe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSubscriptionType;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountPayable;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPeriod;
    private javax.swing.JLabel lblSubscriptionType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JRadioButton rbBasic;
    private javax.swing.JRadioButton rbCorporate;
    private javax.swing.JTextArea taAmountPayable;
    private javax.swing.JTextField tfPayment;
    private javax.swing.JTextField tfPeriod;
    // End of variables declaration//GEN-END:variables
}
